# Step 1: Use official Python image as a base
FROM python:3.9

# S888wdhieiuftep 2: Set the working directory
WORKDIR /app

# Step 3: Copy the Python dependencies file
COPY backend/requirements.txt .

# Step 4: Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Step 5: Copy the Django project files
COPY backend/ .

# Step 6: Expose the port for Django app (usually 8000)
EXPOSE 8000

# Step 7: Run the Django app
CMD ["sh", "entrypoint.sh"]
