# Generated by Django 5.1.6 on 2025-03-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_user_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile_image',
            field=models.ImageField(upload_to='profilfe/'),
        ),
    ]
