# Generated by Django 5.1.6 on 2025-03-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profilfe/'),
        ),
    ]
